### PR TITLE
update to vitest

### PR DESCRIPTION
**Pull request by konsumer**
I was having problem with old version of jest requiring an older version of node.

This switches from jest to vitest, which is faster, more modern, and has a bunch of other features. It also adds a nice watching web UI (`npm run test:watch`) which is great if you like to build features in parallel with unit-tests. It can also do other handy things I didn't enable, like coverage-reports.

Screenshot_2023-03-25_at_3 35 29_PM

### CODE REVIEW

**Review by RobLoach — APPROVED** [review]
Looks great! Is there a way to make vitest output all tests that were run?

```
> vitest run --globals


 RUN  v0.29.7 /home/rob/Documents/node-raylib

WARNING: FILEIO: [missingImage.png] Failed to open file
 · test/node-raylib.test.js (15)

  Node.js bindings for raylib.
    Usage
      $ node-raylib [file]

    Examples
      $ node-raylib - runs data/index.js or index.js
      $ node-raylib core_basic_window.js
 ✓ test/node-raylib.test.js (15)

 Test Files  1 passed (1)
      Tests  15 passed (15)
   Start at  04:00:47
   Duration  707ms (transform 107ms, setup 0ms, collect 37ms, tests 166ms)
```
Knowing 15 tests passed is good, but would be nice to see the full report.

**Comment by konsumer** [comment]
> Knowing 15 tests passed is good, but would be nice to see the full report.

There is an option for that. I will add it.

**Comment by konsumer** [comment]
Ok, added.
Screenshot 2023-03-26 at 12 21 06 PM

**Comment by RobLoach** [comment]
Wooooo

**Pull request merged**
